kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-poc
  namespace: pirani-dev
  labels:
    app: app-poc
spec:
  replicas: 1
  selector:
   matchLabels:
    app: app-poc
  template:
   metadata:
    labels:
     app: app-poc
   spec:
    containers:
    - name: app-poc 
      image: 334789649640.dkr.ecr.us-east-1.amazonaws.com/demo-actions:#{SHA}#
      ports:
      - containerPort: 3000
      resources:
        limits:
          memory: "600Mi"
          cpu: "50m"    
    nodeSelector:
      public: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-poc
  namespace: pirani-dev
spec:
  type: NodePort
  selector:
    app: app-poc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000